# Generated by Django 3.0.9 on 2020-08-14 13:10

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import participants.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=60, verbose_name='Nom')),
                ('last_name', models.CharField(max_length=120, verbose_name='prénoms')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100, validators=[participants.validators.validate_phone_number], verbose_name='Tél')),
                ('gender', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=6, verbose_name='Sexe')),
                ('country', models.CharField(max_length=60, verbose_name='Pays')),
                ('city', models.CharField(max_length=60, verbose_name='Ville')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=60, verbose_name='Nom')),
                ('last_name', models.CharField(max_length=120, verbose_name='prénoms')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100, validators=[participants.validators.validate_phone_number], verbose_name='Tél')),
                ('gender', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=6, verbose_name='Sexe')),
                ('country', models.CharField(max_length=60, verbose_name='Pays')),
                ('city', models.CharField(max_length=60, verbose_name='Ville')),
                ('bachelor_degree', models.CharField(max_length=5, verbose_name='Série de Bac')),
                ('status', models.CharField(choices=[('bachelier', 'bachelier'), ('étudiant', 'étudiant')], max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
