# Generated by Django 3.0.9 on 2020-08-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bachelor_degree',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('F', 'F')], default='A', max_length=5, verbose_name='Série de Bac'),
        ),
    ]
