# Generated by Django 3.0.9 on 2020-08-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_auto_20200814_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Tél'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Tél'),
        ),
    ]
